<#
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#>


# compute the fib to 4 mil

$var = 1, 2

do {
    $nextfib = $var[-1] + $var[-2]

    $var += $nextfib

    Write-Host $var[-1]
} until ($var[-1] -gt 4000000)

Write-Host $var
## list only even

$evenvar = @()

foreach ($item in $var) {

    if ($item % 2 -eq 0) {
        $evenvar += $item
    }
    else {
        
    }
    
}
write-host "even fib to 4mil are"
Write-Host $evenvar